### ISSUE TITLE
Not sure if module should behave such way?

### ISSUE THREAD

**Issue by KacperPerschke** [MakeNowJust/heredoc#11]
## Describe the bug

I'm not sure if such behaviour is inconsistent?

## To Reproduce

**Code**:

```go
package main

import (
	"fmt"

	"github.com/MakeNowJust/heredoc/v2"
)

func main() {
	fmt.Println(heredoc.Doc(`
			Is it a basic indentation level or not?
		  Minus one tab plus two spaces.
			To compare.
	`))
}
```

**Expected**:
```
	Is it a basic indentation level or not?
 Minus one tab plus two spaces.
	To compare.
```
**Actual**:
```
Is it a basic indentation level or not?
 Minus one tab plus two spaces.
To compare.
```
## Environment

- OS: [Go playground](https://go.dev/play/)
- Go: Go release
- Version: ?

**Comment by makenowjust** [comment]
It is intentional behavior. The implementation considers both space and tab are the same (i.e. tab stop is not considered.) Then, the minimal indentation size is 3 in your example and they are trimmed.
