### ISSUE TITLE
invalid v2 versioning

### ISSUE THREAD

**Issue by vvakame** [MakeNowJust/heredoc#7]
## Describe the bug

```
$ go get -u github.com/MakeNowJust/heredoc@v2.0.1
go: finding github.com/MakeNowJust/heredoc v2.0.1
go: finding github.com/MakeNowJust/heredoc v2.0.1
go get github.com/MakeNowJust/heredoc@v2.0.1: github.com/MakeNowJust/heredoc@v2.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
you should make `/v2` dir or v2 branch.

e.g. https://github.com/favclip/ucon/pull/33

## To Reproduce

**Code**: same as below

**Expected**: go get succeed

**Actual**: raise error

## Environment

- OS: macOS
- Go: 1.13.4
- Version: 2.0.1

**Comment by makenowjust** [comment]
Please use `github.com/MakeNowJust/heredoc/v2` (with **`/v2`**!) as module path instead of `github.com/MakeNowJust/heredoc`. It is already specified in `module` directive of `go.mod`.

**Comment by vvakame** [comment]
```
$ go get -u github.com/MakeNowJust/heredoc/v2
go: github.com/MakeNowJust/heredoc/v2/v2@v2.0.1: reading github.com/MakeNowJust/heredoc/v2/v2/go.mod at revision v2/v2.0.1: unknown revision v2/v2.0.1

$ go mod tidy
go: github.com/MakeNowJust/heredoc/v2/v2@v2.0.1: reading github.com/MakeNowJust/heredoc/v2/v2/go.mod at revision v2/v2.0.1: unknown revision v2/v2.0.1
```

🤔
I can't use with `/v2` suffix. is it works well in your environment?
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
This repository is not aligned to `Major branch` and `Major subdirectory` both.

**Comment by makenowjust** [comment]
Sorry, I can't reproduce your error in anyway.

> This repository is not aligned to `Major branch` and `Major subdirectory` both.

No. This repository is aligned to `Major branch` surely because the all procedure are done:

1. Update the go.mod file to include a `/v2` at the end of the module path in the module directive.
2. Update import statements within the module to also use `/v2`.
3. Tag the release with `v2.0.1`.

I guess the cache has gone bad in your case. Please try `rm -rf $GOPATH/mod` (or remove more specified directory).

**Comment by vvakame** [comment]
wow, I tried `go clean -modcache` and `go get -u github.com/MakeNowJust/heredoc/v2`.
problem is solved! 🙇
