### ISSUE TITLE
Using heredoc inside heredoc with JSON : error: invalid character '\n' in string literal after unmarshalling

### ISSUE THREAD

**Issue by Startouf** [MakeNowJust/heredoc#8]
## Describe the bug

When using a `heredoc.Docf` as a string interpolation variable for another `heredoc.Docf` (for instance in the context of building json payloads) with the purpose of (un)marshaling, when there are newlines, the code crashes with `error: invalid character '\n' in string literal`.

After looking at this [StackOverflow](https://stackoverflow.com/questions/38977555/error-embedding-n-into-a-string-literal), it seems it's because we need to double escape the newlines in JSON string literals. So we should provide an example of how to work with JSON in such a way, as I find heredoc to be very convenient for writing JSON-related tests.

Can we add a new method `heredoc.Json/Jsonf(` to handle this case + an example in the readme ? Or is there already a workaround to get this working with `docf` (in which case it would be nice to add this somewhere in the readme) ?

## To Reproduce

**Code**:

```go
import ("github.com/MakeNowJust/heredoc/v2")
func TestHeredocInsideHeredoc(t *testing.T) {
	interpolationHeredoc := heredoc.Docf(`
		Hello,
		%s
	`, "World")
	topLevelHeredoc := heredoc.Docf(`
		{
			"type": "top-level",
			"content": "%s",
		}`, interpolationHeredoc,
	)
	expectedJson := `
		{
			"type": "top-level",
			"content": "Hello,\nWorld"
		}
	`

	expectedBytes := []byte(expectedJson)
	var expectedObject map[string]interface{}
	err := json.Unmarshal(expectedBytes, &expectedObject)
	if err != nil {
		fmt.Println("error:", err)
	}

	expectedBytes = []byte(topLevelHeredoc)
	var actualObject map[string]interface{}
	err = json.Unmarshal(expectedBytes, &actualObject)
	if err != nil {
		fmt.Println("error:", err)
	}

	if diff := deep.Equal(expectedObject, actualObject); diff != nil {
		t.Error(diff)
	}
}

```

**Expected**:

OK

**Actual**: 

```
error: invalid character '\n' in string literal
--- FAIL: TestHeredocInsideHeredoc (0.00s)
    /Users/Cyril/dev/dont-slack-evil/apphome/apphome_test.go:49: [map[content:map[content:Hello,
        World type:top-level] type:nested] != <nil map>]
```

## Environment

- OS: [e.g. Windows, macOS, Linux]
- Go: [e.g. 1.12.9]
- Version: [e.g. 1.0.0]

**Comment by Startouf** [comment]
We can use this workaround to convert the newlines back into \n literals to work with unmarshalling

```
strings.Replace(heredoc.Docf(`
  xxx
`, "\n", `\n`, -1)
```

**Comment by makenowjust** [comment]
Instead of `%s`, you can use `%q` format for quoting and escaping string value.
https://play.golang.org/p/U5EOelh_Gfx

(`%q` produces Go's quoted string value, not JSON's. So, it causes an error sometime. Still it is useful to such quick usage.)

But, building JSON string by formatting function seems very bad. You must use `json.Marshal` to get right result always.
https://play.golang.org/p/vePm5UMnO-S

**Comment by makenowjust** [comment]
@Startouf I think, it is not a bug and to-do for this issue is nothing for now, because your usage looks quite special to me.

> If you want to build JSON string correctly, you should use `json.Marshal`. Otherwise, if you want to get JSON string quickly, you can use `heredoc.Docf` with `%q` at your own risk.

However I don't think this description helps many people...
